package rules

import "github.com/oaslananka/cifence/internal/githubactions"

const ParseRuleID = "CF-PARSE-001"

var Definitions = []githubactions.RuleDefinition{
	{
		ID:          "CF-PERM-001",
		Title:       "permissions: write-all is used",
		Severity:    githubactions.SeverityCritical,
		Description: "Detects workflow-level or job-level permissions: write-all.",
		Remediation: "Replace write-all with explicit least-privilege permissions.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "permissions", "cwe-266"},
	},
	{
		ID:          "CF-PERM-002",
		Title:       "missing explicit permissions block",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects workflows and jobs without explicit permissions blocks.",
		Remediation: "Add explicit permissions, starting from permissions: contents: read.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-002",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "permissions", "cwe-266"},
	},
	{
		ID:          "CF-PERM-003",
		Title:       "dangerous write permission on pull request event",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects write-capable token scopes in workflows triggered by pull_request or pull_request_target.",
		Remediation: "Use read-only permissions for pull request workflows and move writes into trusted follow-up workflows.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-003",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "permissions", "cwe-266"},
	},
	{
		ID:          "CF-PERM-004",
		Title:       "id-token write without trust restriction",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects id-token: write in jobs that do not declare an environment or obvious trusted branch restriction.",
		Remediation: "Restrict OIDC use to trusted branches or protected environments and grant id-token only in the job that needs it.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-004",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "oidc", "cwe-266"},
	},
	{
		ID:          "CF-PERM-005",
		Title:       "job-level permission escalation",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects a job that grants write permissions beyond the workflow baseline.",
		Remediation: "Keep the workflow baseline explicit and narrow; grant elevated scopes only to isolated trusted jobs.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-005",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "permissions", "cwe-266"},
	},
	{
		ID:          "CF-PERM-006",
		Title:       "write token shared with third-party action",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects jobs that combine dangerous write permissions with third-party actions.",
		Remediation: "Split third-party actions into read-only jobs or remove write scopes from jobs that execute external actions.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-006",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "supply-chain", "cwe-829"},
	},
	{
		ID:          "CF-PERM-007",
		Title:       "unknown GitHub token permission scope",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects permissions keys that are not recognized as current GitHub token scopes.",
		Remediation: "Verify the scope against GitHub Actions documentation; remove typos or update CIFence if GitHub introduced a new scope.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-perm-007",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "permissions", "governance"},
	},
	{
		ID:          "CF-ACT-001",
		Title:       "action reference is not pinned to a full commit SHA",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects remote GitHub Actions references that use tags or branches instead of a full commit SHA.",
		Remediation: "Pin to a full commit SHA.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-act-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "supply-chain", "cwe-829"},
	},
	{
		ID:          "CF-ACT-002",
		Title:       "mutable action reference is used",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects mutable GitHub Action refs and Docker latest tags.",
		Remediation: "Pin GitHub actions to full SHA and Docker images to immutable digest.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-act-002",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "supply-chain", "cwe-829"},
	},
	{
		ID:          "CF-ACT-003",
		Title:       "reusable workflow is not pinned to a full commit SHA",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects remote reusable workflow calls that use tags or branches instead of a full commit SHA.",
		Remediation: "Pin remote reusable workflow references to a full commit SHA.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-act-003",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "reusable-workflows", "cwe-829"},
	},
	{
		ID:          "CF-ACT-004",
		Title:       "reusable workflow uses a mutable ref",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects remote reusable workflow calls that use mutable branch-like refs.",
		Remediation: "Pin reusable workflows to full commit SHAs.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-act-004",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "reusable-workflows", "cwe-829"},
	},
	{
		ID:          "CF-INJ-001",
		Title:       "untrusted GitHub context interpolated into run step",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects direct interpolation of pull request, issue, or comment data into shell commands.",
		Remediation: "Pass untrusted values through environment variables and quote them in scripts, or avoid shell execution.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-inj-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "injection", "cwe-78"},
	},
	{
		ID:          "CF-INJ-002",
		Title:       "untrusted context passed into github-script",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects untrusted GitHub context interpolation inside actions/github-script scripts.",
		Remediation: "Read event payload fields from context in JavaScript and validate or escape before use.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-inj-002",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "injection", "cwe-94"},
	},
	{
		ID:          "CF-INJ-003",
		Title:       "untrusted context used in workflow data field",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects untrusted workflow data in cache keys, artifact names, and action command arguments.",
		Remediation: "Use stable trusted identifiers or sanitize untrusted values before using them in workflow control fields.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-inj-003",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "injection", "cwe-20"},
	},
	{
		ID:          "CF-CACHE-001",
		Title:       "cache key uses attacker-controlled context",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects cache keys or restore keys derived from attacker-controlled workflow context.",
		Remediation: "Use trusted stable cache keys and avoid crossing trust boundaries between untrusted PR workflows and privileged workflows.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-cache-001",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "cache", "cwe-829"},
	},
	{
		ID:          "CF-ENV-001",
		Title:       "untrusted context written to GitHub environment file",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects attacker-controlled workflow data appended to GITHUB_ENV, GITHUB_PATH, or GITHUB_OUTPUT.",
		Remediation: "Do not write untrusted event data to environment files; validate and encode values before using workflow command files.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-env-001",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "injection", "cwe-77"},
	},
	{
		ID:          "CF-TRG-001",
		Title:       "pull_request_target checks out untrusted pull request code",
		Severity:    githubactions.SeverityCritical,
		Description: "Detects pull_request_target workflows that checkout untrusted pull request head refs or SHAs.",
		Remediation: "Avoid pull_request_target for untrusted code. Use pull_request with read-only permissions, or never checkout and execute the untrusted head while secrets/write token are available.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-trg-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "pull-request-target", "cwe-829"},
	},
	{
		ID:          "CF-TRG-002",
		Title:       "pull_request_target executes shell commands",
		Severity:    githubactions.SeverityCritical,
		Description: "Detects run steps in pull_request_target workflows.",
		Remediation: "Avoid executing shell commands in pull_request_target unless the workflow never evaluates untrusted pull request data.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-trg-002",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "pull-request-target", "cwe-78"},
	},
	{
		ID:          "CF-TRG-003",
		Title:       "pull_request_target uses third-party action",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects third-party actions in pull_request_target workflows.",
		Remediation: "Use first-party pinned actions only, or move third-party action execution to pull_request with read-only permissions.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-trg-003",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "pull-request-target", "cwe-829"},
	},
	{
		ID:          "CF-TRG-004",
		Title:       "pull_request_target has write token",
		Severity:    githubactions.SeverityCritical,
		Description: "Detects dangerous write permissions in pull_request_target workflows.",
		Remediation: "Set pull_request_target workflows to read-only permissions unless a trusted non-code path requires a narrow write scope.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-trg-004",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "pull-request-target", "cwe-266"},
	},
	{
		ID:          "CF-TRG-005",
		Title:       "pull_request_target uses PR-controlled cache or artifact data",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects cache keys or artifact names in pull_request_target workflows that include untrusted PR-controlled context.",
		Remediation: "Avoid cache or artifact keys derived from untrusted pull request data in privileged workflows.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-trg-005",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "pull-request-target", "cwe-20"},
	},
	{
		ID:          "CF-IMG-001",
		Title:       "job container image is not pinned by digest",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects job container images without an immutable digest.",
		Remediation: "Pin container images with @sha256 digests.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-img-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "containers", "cwe-829"},
	},
	{
		ID:          "CF-IMG-002",
		Title:       "service container image is not pinned by digest",
		Severity:    githubactions.SeverityMedium,
		Description: "Detects service container images without an immutable digest.",
		Remediation: "Pin service images with @sha256 digests.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-img-002",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "containers", "cwe-829"},
	},
	{
		ID:          "CF-IMG-003",
		Title:       "container image uses latest tag",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects job or service container images that use the mutable latest tag.",
		Remediation: "Use a fixed image tag and digest, never latest.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-img-003",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "containers", "cwe-829"},
	},
	{
		ID:          "CF-SEC-001",
		Title:       "reusable workflow inherits all secrets",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects reusable workflow calls with secrets: inherit.",
		Remediation: "Pass only the explicit secrets required by the reusable workflow.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-sec-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "secrets", "cwe-200"},
	},
	{
		ID:          "CF-ART-001",
		Title:       "workflow_run artifact is executed",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects workflow_run jobs that download artifacts and execute shell content in the same trust boundary.",
		Remediation: "Treat upstream artifacts as untrusted; verify provenance and content before execution, or avoid privileged workflow_run execution.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-art-001",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "artifacts", "cwe-829"},
	},
	{
		ID:          "CF-RUN-001",
		Title:       "workflow_run grants dangerous write permissions",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects workflow_run workflows that combine cross-workflow input with dangerous write-capable token scopes.",
		Remediation: "Keep workflow_run jobs read-only unless producer trust, artifact validation, and branch restrictions are explicit.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-run-001",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "workflow-run", "cwe-266"},
	},
	{
		ID:          "CF-RUNNER-001",
		Title:       "self-hosted runner on untrusted trigger",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects self-hosted runner jobs reachable from untrusted workflow triggers.",
		Remediation: "Use GitHub-hosted runners for untrusted contributions or isolate self-hosted runners with trusted labels and protected triggers.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-runner-001",
		Precision:   "medium",
		Tags:        []string{"security", "github-actions", "runners", "cwe-284"},
	},
	{
		ID:          "CF-SUP-001",
		Title:       "expired suppression",
		Severity:    githubactions.SeverityHigh,
		Description: "Detects a configured suppression whose expiry date has passed.",
		Remediation: "Remove expired suppressions or renew them with a current reason and expiry date.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-sup-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "governance"},
	},
	{
		ID:          ParseRuleID,
		Title:       "workflow YAML could not be parsed",
		Severity:    githubactions.SeverityHigh,
		Description: "Reports a workflow file that could not be parsed as YAML.",
		Remediation: "Fix the YAML syntax so the workflow can be analyzed.",
		HelpURI:     "https://github.com/oaslananka/cifence/blob/main/docs/rules.md#cf-parse-001",
		Precision:   "high",
		Tags:        []string{"security", "github-actions", "yaml"},
	},
}

func DefinitionByID(id string) githubactions.RuleDefinition {
	for _, definition := range Definitions {
		if definition.ID == id {
			return definition
		}
	}
	return githubactions.RuleDefinition{
		ID:          id,
		Title:       id,
		Severity:    githubactions.SeverityLow,
		Description: "Unknown rule.",
		Remediation: "Review the finding.",
	}
}
